package com.example.examenmicro.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@DynamoDBTable(tableName = "auto")
@ApiModel(description = "Información del automovil")
@Entity(name ="auto")
public class Auto{
    
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @ApiModelProperty(notes = "Id del auto")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @DynamoDBAttribute(attributeName = "modelo")
    @ApiModelProperty(notes = "Modelo del auto")
    private String modelo;

    @DynamoDBAttribute(attributeName = "precio")
    private Integer precio;

    public Auto(){}

    public Auto(Integer id, String modelo, Integer precio){
        this.id = id;
        this.modelo = modelo;
        this.precio = precio;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public Integer getPrecio() {
        return precio;
    }

    public void setPrecio(Integer precio) {
        this.precio = precio;
    }

    @Override
    public String toString() {
        return "Auto [id=" + id + ", modelo=" + modelo + ", precio=" + precio + "]";
    }

    


}
